#### Import required Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Load the Fuel Dataset

In [2]:
url = "https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv"
Fuel_Data = pd.read_csv(url)

#### Preview Dataset Content (10 randon records)

In [3]:
Fuel_Data.sample(10)

record_id  utility_id_ferc1  report_year  \
13890  f1_fuel_2005_12_191_0_4               191         2005   
22649  f1_fuel_2012_12_195_0_3               195         2012   
24132   f1_fuel_2013_12_72_0_2                72         2013   
7967   f1_fuel_2000_12_27_2_12                27         2000   
8734   f1_fuel_2001_12_127_1_7               127         2001   
12610  f1_fuel_2004_12_191_0_2               191         2004   
7428    f1_fuel_2000_12_55_3_5                55         2000   
13852   f1_fuel_2005_12_56_2_2                56         2005   
17475  f1_fuel_2008_12_89_1_10                89         2008   
29265  f1_fuel_2018_12_56_0_11                56         2018   

          plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
13890             tecumseh                 gas       mcf            842.0   
22649            pulliam 5                 gas       mcf          34644.0   
24132         clifty creek                 oil       gal         547049.0   
7967   east bend #2 - cg&e                 oil       bbl          10917.0   
8734           sporn-total                coal       ton        2264223.0   
12610             tecumseh                 gas       mcf          93000.0   
7428       univ.of florida                 gas       mcf        3190457.0   
13852      st. johns river                coal       ton         695245.0   
17475     sycamore-2 units                 gas       mcf          16025.0   
29265              riviera                 oil       bbl           7526.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
13890             1.014000                     11.510   
22649             1.021000                      3.550   
24132             5.712000                      3.268   
7967              5.753286                     30.733   
8734             23.614000                     26.731   
12610             1.017000                      6.970   
7428              1.043000                      4.086   
13852            24.026000                     44.786   
17475             1.017000                     16.774   
29265             5.917002                    120.980   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
13890                        11.510             11.35000  
22649                         3.550              3.48000  
24132                         3.279             24.02638  
7967                         37.639              5.34200  
8734                         31.841              1.13200  
12610                         6.970              6.86000  
7428                          4.086              3.91900  
13852                        44.786              1.86400  
17475                        16.774             16.49600  
29265                       120.980             20.44600

#### Summary Statistics of the Dataset

In [4]:
Fuel_Data.describe(include='all')

record_id  utility_id_ferc1   report_year  \
count                     29523      29523.000000  29523.000000   
unique                    29523               NaN           NaN   
top     f1_fuel_2005_12_151_0_7               NaN           NaN   
freq                          1               NaN           NaN   
mean                        NaN        118.601836   2005.806050   
std                         NaN         74.178353      7.025483   
min                         NaN          1.000000   1994.000000   
25%                         NaN         55.000000   2000.000000   
50%                         NaN        122.000000   2006.000000   
75%                         NaN        176.000000   2012.000000   
max                         NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6         9              NaN   
top           big stone                 gas       mcf              NaN   
freq                156               11486     11354              NaN   
mean                NaN                 NaN       NaN     2.622119e+06   
std                 NaN                 NaN       NaN     9.118004e+06   
min                 NaN                 NaN       NaN     1.000000e+00   
25%                 NaN                 NaN       NaN     1.381700e+04   
50%                 NaN                 NaN       NaN     2.533220e+05   
75%                 NaN                 NaN       NaN     1.424034e+06   
max                 NaN                 NaN       NaN     5.558942e+08   

        fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
count          29523.000000               29523.000000   
unique                  NaN                        NaN   
top                     NaN                        NaN   
freq                    NaN                        NaN   
mean               8.492111                 208.649031   
std               10.600220                2854.490090   
min                0.000001                -276.080000   
25%                1.024000                   5.207000   
50%                5.762694                  26.000000   
75%               17.006000                  47.113000   
max              341.260000              139358.000000   

        fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
count                   2.952300e+04         29523.000000  
unique                           NaN                  NaN  
top                              NaN                  NaN  
freq                             NaN                  NaN  
mean                    9.175704e+02            19.304354  
std                     6.877593e+04          2091.540939  
min                    -8.749370e+02           -41.501000  
25%                     3.778500e+00             1.940000  
50%                     1.737100e+01             4.127000  
75%                     4.213700e+01             7.745000  
max                     7.964521e+06        359278.000000

### Question 1

In [19]:
A = [1,2,3,4,5,6]
B = [13, 21, 34]
A.extend(B)
A


[1, 2, 3, 4, 5, 6, 13, 21, 34]

### Question 2

In [20]:
Z = np.identity(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Question 3

In [23]:
Fuel_Type_Code_Average = Fuel_Data.groupby('fuel_type_code_pudl', as_index=False)['fuel_cost_per_unit_burned'].mean()
Fuel_Type_Code_Average.loc[Fuel_Type_Code_Average['fuel_cost_per_unit_burned'].idxmin()]

fuel_type_code_pudl              gas
fuel_cost_per_unit_burned    13.6594
Name: 1, dtype: object

### Question 4

In [29]:
Fuel_Data['fuel_mmbtu_per_unit'].describe(include='np.number').round(2)

count    29523.00
mean         8.49
std         10.60
min          0.00
25%          1.02
50%          5.76
75%         17.01
max        341.26
Name: fuel_mmbtu_per_unit, dtype: float64

### Question 5

In [32]:
fuel_qty_burned_skew = Fuel_Data['fuel_qty_burned'].skew(axis = 0, skipna = True).round(2)
fuel_qty_burned_kurtosis = Fuel_Data['fuel_qty_burned'].kurtosis(axis = 0, skipna = True).round(2)
print(fuel_qty_burned_skew)
print(fuel_qty_burned_kurtosis)

15.85
651.37


### Question 6

In [38]:
Feature_missing_value = Fuel_Data.columns[Fuel_Data.isnull().any()]
Number_of_missing_value = Fuel_Data.isnull().any(axis = 1).sum()
Percentage_of_missing_value = (Fuel_Data['fuel_unit'].isnull().sum() * 100 / len(Fuel_Data)).round(3)
print (Feature_missing_value)
print(Number_of_missing_value)
print(Percentage_of_missing_value)

Index(['fuel_unit'], dtype='object')
180
0.61


### Question 7

In [39]:
Fuel_Data['fuel_unit'].dtypes

dtype('O')

### Question 8

In [40]:
corr_matrix = Fuel_Data.corr()
print(corr_matrix["fuel_cost_per_unit_burned"].sort_values(ascending=False))

fuel_cost_per_unit_burned       1.000000
report_year                     0.013599
fuel_cost_per_unit_delivered    0.011007
fuel_cost_per_mmbtu            -0.000437
fuel_mmbtu_per_unit            -0.010034
fuel_qty_burned                -0.018535
utility_id_ferc1               -0.037863
Name: fuel_cost_per_unit_burned, dtype: float64


### Question 9

In [42]:
Fuel_Cost_1994 = Fuel_Data[(Fuel_Data['report_year'] == 1994)&(Fuel_Data['fuel_type_code_pudl'] == 'coal')]['fuel_cost_per_unit_burned'].sum()
Fuel_Cost_1998 = Fuel_Data[(Fuel_Data['report_year'] == 1998)&(Fuel_Data['fuel_type_code_pudl'] == 'coal')]['fuel_cost_per_unit_burned'].sum()
perc_change = ((Fuel_Cost_1998-Fuel_Cost_1994)/Fuel_Cost_1994)*100
perc_change

-20.56765451826053

### Question 10